# Generated by Django 3.0.3 on 2021-01-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=12)),
            ],
        ),
    ]
