# Generated by Django 3.0.3 on 2020-12-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.IntegerField()),
                ('sname', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=20)),
                ('fees', models.FloatField()),
            ],
        ),
    ]
