# Generated by Django 3.0.3 on 2020-12-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField()),
                ('coursename', models.CharField(max_length=50)),
                ('coursefees', models.CharField(max_length=20)),
            ],
        ),
    ]
